apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: delivereats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: us-central1-docker.pkg.dev/proyecto-sa-492706/delivereats/orders-service:v1.0
        ports:
        - containerPort: 50053
          name: grpc
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: catalog-service-config
              key: REDIS_HOST
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: catalog-service-config
              key: RABBITMQ_URL
        - name: CATALOG_GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: CATALOG_SERVICE_URL
        - name: AUTH_GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: AUTH_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: orders-service-config
              key: NOTIFICATION_SERVICE_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "700m"
        livenessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: delivereats
spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-service-hpa
  namespace: delivereats
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
