apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "50051"
  DB_HOST: "34.55.202.138"
  DB_PORT: "3306"
  DB_NAME: "auth_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3002"
  DB_HOST: "34.55.202.138"
  DB_PORT: "3306"
  DB_NAME: "catalog_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://delivereats:rabbitmq2024@rabbitmq-service.delivereats.svc.cluster.local:5672/"
  RABBITMQ_QUEUE: "order_events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3003"
  DB_HOST: "34.55.202.138"
  DB_PORT: "3306"
  DB_NAME: "orders_db"
  RABBITMQ_URL: "amqp://delivereats:rabbitmq2024@rabbitmq-service.delivereats.svc.cluster.local:5672/"
  RABBITMQ_QUEUE: "order_events"
  CATALOG_SERVICE_URL: "catalog-service:50052"
  AUTH_SERVICE_URL: "auth-service:50051"
  NOTIFICATION_SERVICE_URL: "notification-service:50055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "50054"
  DB_HOST: "34.55.202.138"
  DB_PORT: "3306"
  DB_NAME: "delivery_db"
  ORDERS_SERVICE_URL: "http://orders-service:50053"
  NOTIFICATION_SERVICE_URL: "http://notification-service:50055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "50055"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM: "noreply@delivereats.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3000"
  AUTH_SERVICE_URL: "auth-service:50051"
  CATALOG_SERVICE_URL: "catalog-service:50052"
  ORDERS_SERVICE_URL: "orders-service:50053"
  DELIVERY_SERVICE_URL: "delivery-service:50054"
  NOTIFICATION_SERVICE_URL: "notification-service:50055"
  FX_SERVICE_URL: "fx-service:5000"
  PAYMENT_SERVICE_URL: "payment-service:3006"
  FRONTEND_URL: "https://frontend-681870377764.us-central1.run.app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3006"
  DB_HOST: "34.55.202.138"
  DB_PORT: "3306"
  DB_NAME: "payment_db"
  ORDERS_SERVICE_URL: "http://orders-service:50053"
  FX_SERVICE_URL: "http://fx-service:5000"
  NOTIFICATION_SERVICE_URL: "http://notification-service:50055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fx-service-config
  namespace: delivereats
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  GRPC_PORT: "50053"
  GRPC_MAX_WORKERS: "10"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  FLASK_DEBUG: "false"
  FX_API_BASE_URL: "https://open.er-api.com/v6/latest"
  FX_API_TIMEOUT: "10"
  CACHE_TTL: "360"
  FALLBACK_TTL: "86400"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivereats-config
  namespace: delivereats
data:
  apiGatewayUrl: "http://api-gateway:3000"
